---
- name: Playbook for Webserver
  hosts: localhost
  become: yes

  roles:
    - role: software/git
    - role: software/php
    - role: software/apache2
    - role: software/mysqlClient
    - role: software/composer
  