---
- name: Install mysql-client
  apt:
    name: mysql-client
    state: present

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    login_user: "${{AWS__Database_username}}"
    login_password: "${{AWS__Database_password}}"
    login_host: "${{AWS__Database_ip}}"
    state: import
    name: employees
    target: /var/www/html/2TIN_ResearchProject/employees.sql