---
- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Set default root directory
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: 'DocumentRoot /var/www/html'
    line: DocumentRoot /var/www/html/2TIN_ResearchProject

- name: Template config_php
  template:
    src: config.sh.j2
    dest: /var/www/html/2TIN_ResearchProject/config.php

- name: Template index_php
  template:
    src: index.sh.j2
    dest: /var/www/html/2TIN_ResearchProject/index.php
  notify: Started Apache2